#服务端配置
server:
  port: 8090   #端口号
  servlet:
    session:
      timeout: 120m #设置过期时间为120分钟
mybatis:
  mapper-locations: classpath*:mapper/*.xml #扫描mybatis的mapper.xml文件
  type-aliases-package: com.lcvc.intern_choose.model #起别名，指向实体类的位置，可省略写mybatis的xml中的resultType的全路径，取代<typeAlias alias="Admin" type="com.ljy.maven_github_ssm.model.Admin"/>
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/intern_choose?characterEncoding=utf-8&serverTimezone=CTT
    username: lcvc
    password: lcvc123456
    driverClassName: com.mysql.cj.jdbc.Driver